server:
  port: 8001
eureka:
  client:
    registry-fetch-interval-seconds: 30
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8001/eureka

security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456

